### ISSUE TITLE
Performance? Do a single Publish for all client subs

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes-cached-persistence#6]
Instead of a single publish per subscription [here](https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L107) If we do a publish per client (subs) will it help performance @mcollina ?

I think changing https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L100 to `function brokerPublish (subs, cb)` would need changing aede

**Comment by mcollina** [comment]
Definitely, go ahead :).

**Comment by behrad** [comment]
https://github.com/mcollina/aedes-cached-persistence/pull/7
